FROM debian:bullseye-slim

WORKDIR /app

COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:${BRANCH} /tmp/builder/target/release/airdao-gov-portal-db .
COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:${BRANCH} /tmp/builder/gov-portal-db /app/gov-portal-db

RUN apt-get update && apt-get install -y lsb-release ca-certificates libssl-dev && apt-get clean all

CMD ["./airdao-gov-portal-db"]
