FROM debian:bullseye-slim

WORKDIR /app

COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:main /tmp/builder/target/release/airdao-gov-portal-db .

RUN mkdir -p ./config

CMD ["./airdao-gov-portal-db"]
