FROM debian:bullseye-slim

WORKDIR /app

COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:main /tmp/builder/target/release/airdao-gov-portal-db .
COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:main /tmp/builder/gov-portal-db /app/gov-portal-db

CMD ["./airdao-gov-portal-db"]
