FROM debian:bullseye-slim

ARG BRANCH

WORKDIR /app

COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:${BRANCH} /tmp/builder/target/release/airdao-gov-user-verifier .
COPY --from=ghcr.io/ambrosus/airdao-gov-user-binary:${BRANCH} /tmp/builder/config /app/config

RUN apt-get update && apt-get install -y lsb-release ca-certificates libssl-dev && apt-get clean all

CMD ["./airdao-gov-user-verifier"]
