[package]
name = "event-signature-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
sha3 = { workspace = true }
ethereum-types = { workspace = true }
